### ISSUE TITLE
Story title HTML Entities are encoded

### ISSUE THREAD

**Issue by codepuncher** [pixelcollective/ndncollective.org#50]
Was looking for mutombo and stumbled across this.

![image](https://user-images.githubusercontent.com/8135396/52822702-5fb85400-30aa-11e9-9e9e-e296aa9452cc.png)

https://github.com/pixelcollective/ndncollective.org/blob/8596462e8d508e231acdd57e4826c18398dcd7a2/ndncollective.org/web/app/themes/ndncollective/resources/views/partials/cards/card.blade.php#L10

Replace with
```blade
<h3 class="entry-title"><a href="{{ get_permalink() }}">@php the_title() @endphp</a></h3> 
```

**Comment by codepuncher** [comment]
Duplicate of #49!

**Comment by kellymears** [comment]
I’ll have to refer you to issue #49
